# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='credentials',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
