# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0006_auto_20170211_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='exam', max_length=100)),
                ('exam_date', models.DateTimeField(null=True)),
                ('exam_duration', models.IntegerField(default=60)),
                ('answer_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.AnswerKey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='No Question', max_length=1000)),
                ('option_a', models.CharField(default='no_option', max_length=1000)),
                ('option_b', models.CharField(default='no_option', max_length=1000)),
                ('option_c', models.CharField(default='no_option', max_length=1000)),
                ('option_d', models.CharField(default='no_option', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_question', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.QuestionPaper'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.Question'),
        ),
    ]
