# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0007_auto_20170214_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_duration',
        ),
    ]
