# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0008_auto_20170215_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.QuestionPaper'),
        ),
    ]
