# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0009_auto_20170215_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.DateTimeField(null=True),
        ),
    ]
