# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0011_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
