# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0012_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_paper',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.QuestionPaper'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.Credentials'),
        ),
        migrations.AlterField(
            model_name='student',
            name='credentials',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.Credentials'),
        ),
    ]
