# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0013_auto_20170218_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
