# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0014_auto_20170218_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQ.Course'),
        ),
    ]
