# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0017_auto_20170219_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_paper',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='MCQ.QuestionPaper'),
        ),
    ]
