# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0019_auto_20170219_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('faculty', 'faculty')], max_length=10, null=True),
        ),
    ]
